# SPDX-FileCopyrightText: 2026 GARDENA GmbH
#
# SPDX-License-Identifier: Apache-2.0

changelog:
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: ✨ Enhancements
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
